//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareRentalRecord
    {
        public int id { get; set; }
        public string CustName { get; set; }
        public Nullable<System.DateTime> DateRented { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> TypeOfHardwareId { get; set; }
    
        public virtual TypesOfHardware TypesOfHardware { get; set; }
    }
}
